platform: linux

#image_resource:
#  type: docker-image
#  source:
#    repository: aguseka/concourse-poc
#    tag: "0.0.1-SNAPSHOT"

inputs:
- name: source-code

run:
  path: source-code/ci/tasks/package.sh